create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  massage_count integer not null default 0 check (massage_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  is_package boolean not null default false,
  massage_count integer not null default 1 check (massage_count >= 1),
  value_cents integer not null default 0 check (value_cents >= 0),
  address text,
  appointment_date date not null,
  start_time time not null,
  end_time time,
  status text not null default 'agendado' check (status in ('agendado','confirmado','concluido','cancelado')),
  paid boolean not null default false,
  paid_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

ALTER TABLE public.clients
ADD COLUMN user_id bigint REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.appointments
ADD COLUMN user_id bigint REFERENCES public.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_clients_user_id
ON public.clients(user_id);

CREATE INDEX IF NOT EXISTS idx_appointments_user_id
ON public.appointments(user_id);

create index if not exists idx_clients_name_lower on public.clients (lower(name));
create index if not exists idx_appointments_date_time on public.appointments (appointment_date,start_time);
create index if not exists idx_appointments_client on public.appointments (client_id);
create index if not exists idx_appointments_payment on public.appointments (paid,appointment_date);

alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.appointments enable row level security;
